---
- name: Register public user
  user: name=nas-public shell=/usr/sbin/nologin system=no

- name: Register user
  user: name=nas-user groups=nas-public password={{ user_pass }} shell=/bin/bash

- name: Register admin user
  user: name=nas-admin groups=admin,nas-user,nas-public system=yes password={{ admin_pass }} shell=/bin/bash


