---
- name: Register public users
  user: name={{ item.name }} shell=/usr/sbin/nologin system=no
        password={{ item.pass.hash|default(empty_password.hash, true) }}
  with_items: nas_public_users

- name: Register users
  user: name={{ item.name }} groups={{ item.groups }}
        password={{ item.pass.hash|default(empty_password.hash, true) }}
        shell=/bin/bash
  with_items: nas_users

- name: Register admin users
  user: name={{ item.name }} groups={{ item.groups }}
        system=yes password={{ item.pass.hash|default(empty_password.hash, true) }}
        shell=/bin/bash
  with_items: nas_admins


