---
# Expect ubuntu-server with user `nas-admin` + ssh access (private key ~/.ssh/nas)
#
- hosts: nas
  remote_user: nas-admin
  sudo: yes
  roles:
  - role: common
  - role: nas.users
  - role: nas.fs
  - role: minidlna
  - role: deluge
  - role: samba
  - role: btsync
  - role: dropbox
  - role: udpxy
