---
- name: restart procps
  service: name=procps state=restarted

- name: regenerate locales
  command: locale-gen {{ item }}
  with_items: locales
  notify:
  - update locales

- name: update locales
  command: {{ item }}
  with_items:
  - update-locale
  - dpkg-reconfigure locales
